CREATE DATABASE IF NOT EXISTS `todoapp` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE `todoapp`;

CREATE TABLE IF NOT EXISTS `todos` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `title` VARCHAR(255) NOT NULL,
    `description` TEXT,
    `completed` TINYINT(1) DEFAULT 0,
    `created` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `modified` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
